#!/bin/bash

> full.log

sudo grep "(WW)" /var/log/anaconda/X.log | sed 's/(WW)/Warning: /' >> full.log
sudo grep "(II)" /var/log/anaconda/X.log | sed 's/(II)/Information: /' >> full.log
cat full.log
