#!/bin/bash

sleep 10000 &

PID_SLEEP=$!

cd /proc/$PID_SLEEP

sudo cat stack | tail -5

echo

cat status | awk '{
    if ($1 == "Name:") {print $1 " " $2}
    if ($1 == "PPid:") {print $1 " " $2}
    if ($1 == "Kthread:") {print $1 " " $2}
    if ($1 == "Threads:") {print $1 " " $2}
}'

echo

cat status | awk '{
    if ($1 == "Tgid:") {print $1 " " $2}
    if ($1 == "Pid:") {print $1 " " $2}
}'

# почему совпадают:
# потому что Tgid (Thread Group ID) это процесс потока
# и sleep это процесс одного потока с PID этого процесса

# если бы процесс создавал доп потоки, то у каждого был бы свой PID
# но Tgid был бы у всех одинаковый

kill $PID_SLEEP